import Head from "next/head";
import Header from "../components/header";
import Slider from "../components/slider";
import Filters from "../components/filters";
import EventCard from "../components/eventCard";
import styles from "../styles/Home.module.css";

export default function Home({ data }) {
  const images = [];

  console.log(data);

  for(let i = 0; i < 5; i++) {
    images[i] = data.items[i];
  }

  const items = data.items;

  return (
    <div className={styles.mainContainer}>
      <Head>
        <title>
          Etkinliğini Bul - Şehrindeki En Popüler Etkinlikleri Görüntüle
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={styles.subContainer}>
        <div>
          <Slider images={images} />
        </div>
        <div className={styles.titles}>
            <h3 className={styles.firstTitle}>Filtreler</h3>
            <h3 className={styles.secondTitle}>Güncel Etkinlikler</h3>
        </div>
        <div className={styles.subsubContainer}>
          <div className={styles.filters}>
            <Filters />
          </div>
          <div className={styles.eventCard}>
            {
              items.map(item => {
                let date = new Date(item.start);
                return <EventCard key={item.id} eventTitle={item.name} url={item.url} eventPrice={item.is_free} eventPlace={item.venue.name} eventImg={item.poster_url} eventDate={date.toDateString()} />
              })
            }
          </div>
        </div>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const response = await fetch("https://backend.etkinlik.io/api/v2/events", {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
      "X-Etkinlik-token": "92510ee702346c171e6e27c6566af993",
    },
  });
  const data = await response.json();

  return {
    props: {
      data,
    },
  };
}
